scribabot:
  token:
  secret:
  confirmation-code:
  keyboards-folder: keyboards/
  vk-api-version: "5.100"

call:
  rest:
    prefix:

scheduled:
  schedule-daily-notification-service:
    cron: 1 0 * * * *
  schedule-tomorrow-notification-service:
    cron: 5 0 * * * *

server:
  port:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: