scriba-bot:
  token:
  secret:
  confirmation-code:
  keyboards-folder: keyboards/
  vk-api-version: 5.100

call:
  rest:
    prefix: http://localhost:8080/api/v1.0/

scheduled:
  daily-notification-service:
    hour: 1

server:
  port:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: