scriba-bot:
  vk:
    token:
    secret:
    confirmation-code:
    api-version:
    url:
    mentioned-names: "example1,@example2"
  tg:
    name:
    token:

call:
  rest:
    prefix:

project:
  version: '@project.version@'

scheduled:
  schedule-today-notification-service:
    cron:
  schedule-tomorrow-notification-service:
    cron:
  schedule-after-tomorrow-notification-service:
    cron:
  default-hour-for-send:

week-type:
  access-token:

vk-executor:
  core-pool-size:
  max-pool-size:
  queue-capacity:
  thread-name-prefix:

server:
  port:

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: