scriba-bot:
  token:
  secret:
  confirmation-code:
  keyboards-folder:
  vk-api-version:
  vk-url:

call:
  rest:
    prefix:

scheduled:
  schedule-daily-notification-service:
    cron:
  schedule-tomorrow-notification-service:
    cron:

week-type:
  access-token:

server:
  port:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: