scriba-bot:
  token:
  secret:
  confirmation-code:
  keyboards-folder: keyboards/

call:
  rest:
  prefix: http://localhost:8080/api/v1.0/

server:
  port:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: