scriba-bot:
  token: ${SCRIBA_BOT_TOKEN}
  secret: ${SCRIBA_BOT_SECRET}
  confirmation-code: ${SCRIBA_BOT_CONFIRMATION_CODE}
  keyboards-folder: keyboards/

spring:
  datasource:
    url: ${SCRIBA_BOT_DATABASE_URL}
    username: ${SCRIBA_BOT_DATABASE_USERNAME}
    password: ${SCRIBA_BOT_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: ${SCRIBA_BOT_JPA_HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: update