scriba-bot:
  token:
  secret:
  confirmation-code:
  keyboards-folder:
  vk-api-version:
  vk-url:
  mentioned-names: "example1,@example2"

call:
  rest:
    prefix:

scheduled:
  schedule-today-notification-service:
    cron:
  schedule-tomorrow-notification-service:
    cron:
  schedule-after-tomorrow-notification-service:
    cron:

week-type:
  access-token:

server:
  port:

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: