package com.scribassu.scribabot.entities.notifications;

public enum NotificationType {
    FULL_TIME_TODAY, FULL_TIME_TOMORROW,
    EXAM_PERIOD_TODAY, EXAM_PERIOD_TOMORROW, EXAM_PERIOD_AFTER_TOMORROW,
    EXTRAMURAL_EVENT_TODAY, EXTRAMURAL_EVENT_TOMORROW, EXTRAMURAL_EVENT_AFTER_TOMORROW
}
